import type { Metadata } from "next";
import { Spline_Sans, Spline_Sans_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navigation from "./components/Navigation";

const splineSans = Spline_Sans({
  variable: "--font-spline-sans",
  subsets: ["latin"]
})

const splineSansMono = Spline_Sans_Mono({
  variable: "--font-spline-sans-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${splineSans.variable} ${splineSansMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Navigation />
        <main className="h-full">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
