import type { Metadata } from "next";
import { Spline_Sans, Spline_Sans_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navigation from "./components/Navigation";
import { getCurrentUser } from "@/lib/session";
import { AuthProvider } from "@/providers/AuthProvider";

const splineSans = Spline_Sans({
  variable: "--font-spline-sans",
  subsets: ["latin"]
})

const splineSansMono = Spline_Sans_Mono({
  variable: "--font-spline-sans-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body
        className={`${splineSans.variable} ${splineSansMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <AuthProvider user={user}>
          <Navigation />
          <main className="h-full">
            {children}
          </main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
